YAPP-Github/23rd-Android-Team-2-BE

.docker/Dockerfile, .docker/docker-compose.yml, .github/workflows/build.yml, .github/workflows/deploy-dev.yml, build.gradle, settings.gradle, src/main/resources/application.yml
- build/deploy script 추가
- 환경 변수 관리(.env)
- actuator 추가
actuator는 health check용으로 추가했습니다.
NCP 관련 문서는 notion에 추가할게요~ (env file, 계정 정보 등)
=> feat: deploy setting

.docker/Dockerfile, .docker/docker-compose.yml, .github/workflows/build.yml, .github/workflows/deploy-dev.yml, build.gradle, settings.gradle, src/main/resources/application.yml
- build/deploy script 추가
- 환경 변수 관리(.env)
- actuator 추가
actuator는 health check용으로 추가했습니다.
NCP 관련 문서는 notion에 추가할게요~ (env file, 계정 정보 등)
=> feat: deploy setting

src/main/java/com/moneymong/domain/user/User.java, src/main/java/com/moneymong/domain/user/repository/UserRepository.java, src/main/java/com/moneymong/domain/useruniversity/UserUniversity.java, src/main/java/com/moneymong/domain/useruniversity/repository/UserUniversityRepository.java, src/main/java/com/moneymong/global/config/jpa/JpaConfig.java, src/main/java/com/moneymong/global/domain/BaseEntity.java, src/main/resources/application.yml
user, user_university Entity를 추가합니다.
- BaseEntity 추가
- User, UserUniversity 추가
userToken은 외부에 노출되는 유저의 고유 식별자입니다.
soft delete를 적용합니다.
=> 유저와 유저의 학교 정보를 저장하는 엔티티를 생성한다.

.github/workflows/build.yml
build하는 workflow가 실패하는 상황이라,
요 PR에 커밋을 쌓으면서 해결합니다.
=> chore: workflow에 mysql 실행 추가

build.gradle, src/main/resources/application-security.yml, src/main/resources/application.yml
- JWT 라이브러리 추가
- yml 파일 추가
JWT_SECRET_KEY는 문서에 업데이트 해놓을게요
=> setting: JWT 라이브러리 추가 및 설정

src/main/java/com/moneymong/domain/ledger/entity/Ledger.java, src/main/java/com/moneymong/domain/ledger/entity/LedgerDetails.java, src/main/java/com/moneymong/domain/ledger/entity/LedgerReceipts.java, src/main/java/com/moneymong/domain/ledger/entity/LedgerUsers.java, src/main/java/com/moneymong/domain/ledger/entity/enums/FundType.java, src/main/java/com/moneymong/domain/ledger/entity/enums/LedgerUserRoleType.java, src/main/java/com/moneymong/domain/university/University.java, src/main/java/com/moneymong/domain/user/entity/User.java, src/main/java/com/moneymong/domain/user/entity/UserUniversity.java, src/main/java/com/moneymong/domain/user/repository/UserRepository.java, src/main/java/com/moneymong/domain/user/repository/UserUniversityRepository.java
대학교 검색과 장부 기능에 필요한 Entity를 설계합니다.
- **대학교 검색, 장부, 장부 회원, 장부 상세 내역, 장부 영수증** 엔티티 설계하였습니다.
- 엔티티 생성
=> feat: 대학교, 장부 Entity 설계 

src/main/java/com/moneymong/domain/agency/entity/Agency.java, src/main/java/com/moneymong/domain/agency/entity/AgencyUser.java, src/main/java/com/moneymong/domain/agency/entity/enums/AgencyType.java, src/main/java/com/moneymong/domain/agency/entity/enums/AgencyUserRole.java, src/main/java/com/moneymong/domain/agency/repository/AgencyRepository.java, src/main/java/com/moneymong/domain/agency/repository/AgencyUserRepository.java, src/main/java/com/moneymong/domain/user/entity/UserUniversity.java
Agency, AgencyUser Entity를 생성합니다.
아래는 App 실행 결과입니다.
=> feat: Agency, AgencyUser Entity를 생성한다.

src/main/java/com/moneymong/global/security/token/service/JwtTokenProvider.java, src/main/java/com/moneymong/global/security/token/service/TokenService.java, src/test/java/com/moneymong/global/security/token/JwtTokenProviderTest.java
JWT Claim을 Map<Long, String>에서 String으로 변경합니다.
권한이 필요한 기능은 JWT 필터가 아니라 애플리케이션 내에서 코드로 구현할 예정입니다.
JWT는 로그인 여부만 검사합니다 !
=> refactor: JWT Claim을 변경한다.

src/main/java/com/moneymong/domain/agency/entity/Agency.java, src/main/java/com/moneymong/domain/agency/entity/AgencyUser.java, src/main/java/com/moneymong/domain/user/entity/UserUniversity.java, src/main/java/com/moneymong/global/config/jpa/JpaConfig.java, src/main/java/com/moneymong/global/security/token/entity/RefreshToken.java, src/main/java/com/moneymong/global/security/token/repository/RefreshTokenRepository.java
RefreshToken Entity를 추가합니다.
PK는 UUID로 생성할 무작위 토큰입니다.
+ 다른 Entity에 누락된 부분들(Builder, BaseEntity) 추가했습니다.
=> feat: RefreshToken Entity를 추가한다.

.github/workflows/deploy-dev.yml, src/main/java/com/moneymong/global/config/docs/OpenApiConfig.java, src/main/java/com/moneymong/global/config/web/WebConfig.java
Swagger Test 시 발생하는 cors 문제를 해결합니다.
1. WebMvcConfigurer.addCorsMappings() 추가
=> fix: cors 설정을 추가한다.

src/main/java/com/moneymong/domain/ledger/api/LedgerController.java, src/main/java/com/moneymong/domain/ledger/api/LedgerDetailController.java, src/main/java/com/moneymong/domain/ledger/api/response/LedgerDetailInfoView.java, src/main/java/com/moneymong/domain/ledger/entity/LedgerDetail.java, src/main/java/com/moneymong/domain/ledger/entity/LedgerDocument.java, src/main/java/com/moneymong/domain/ledger/entity/LedgerReceipt.java, src/main/java/com/moneymong/domain/ledger/repository/LedgerDetailRepository.java, src/main/java/com/moneymong/domain/ledger/repository/LedgerDocumentRepository.java, src/main/java/com/moneymong/domain/ledger/repository/LedgerReceiptRepository.java, src/main/java/com/moneymong/domain/ledger/service/manager/LedgerDetailManager.java, src/main/java/com/moneymong/domain/ledger/service/manager/LedgerDocumentManager.java, src/main/java/com/moneymong/domain/ledger/service/manager/LedgerManager.java, src/main/java/com/moneymong/domain/ledger/service/manager/LedgerReceiptManager.java, src/main/java/com/moneymong/domain/ledger/service/mapper/LedgerAssembler.java, src/main/java/com/moneymong/domain/ledger/service/reader/LedgerDetailReader.java, src/main/java/com/moneymong/global/constant/MoneymongConstant.java, src/main/java/com/moneymong/global/exception/enums/ErrorCode.java
장부 상세 내역 조회 기능을 개발합니다.
- 장부 상세 내역 조회 기능을 구현하였습니다.
- 장부 상세 내역 조회 시 장부 상세 내역 검증이 수행됩니다.
- 성공 응답
- 예외 검증
- 장부 상세 내역 검증
=> feat: 장부 상세 내역 조회 API

src/main/java/com/moneymong/domain/ledger/api/LedgerController.java, src/main/java/com/moneymong/domain/ledger/api/LedgerReceiptController.java, src/main/java/com/moneymong/domain/ledger/api/request/CreateLedgerReceiptRequest.java, src/main/java/com/moneymong/domain/ledger/service/manager/LedgerManager.java, src/main/java/com/moneymong/domain/ledger/service/manager/LedgerReceiptManager.java, src/main/java/com/moneymong/global/exception/enums/ErrorCode.java
- 장부 영수증 내역 추가 및 삭제 기능 구현하였습니다.
=> feat: 장부 영수증 내역 추가 및 삭제 API

src/main/java/com/moneymong/domain/ledger/api/LedgerDetailController.java, src/main/java/com/moneymong/domain/ledger/api/LedgerDocumentController.java, src/main/java/com/moneymong/domain/ledger/api/LedgerReceiptController.java, src/main/java/com/moneymong/domain/ledger/api/request/CreateLedgerDocumentRequest.java, src/main/java/com/moneymong/domain/ledger/repository/LedgerDocumentRepository.java, src/main/java/com/moneymong/domain/ledger/repository/LedgerReceiptRepository.java, src/main/java/com/moneymong/domain/ledger/service/manager/LedgerDetailManager.java, src/main/java/com/moneymong/domain/ledger/service/manager/LedgerDocumentManager.java, src/main/java/com/moneymong/domain/ledger/service/manager/LedgerManager.java, src/main/java/com/moneymong/global/exception/enums/ErrorCode.java
- 장부 증빙자료 추가 및 삭제 기능 구현하였습니다.
- 장부 상세 내역 삭제 기능 구현하였습니다.
=> feat: 장부 증빙 자료 추가 및 삭제, 상세 내역 삭제 구현

src/main/java/com/moneymong/domain/ledger/api/LedgerController.java, src/main/java/com/moneymong/domain/ledger/api/LedgerDetailController.java, src/main/java/com/moneymong/domain/ledger/api/LedgerDocumentController.java, src/main/java/com/moneymong/domain/ledger/api/LedgerReceiptController.java, src/main/java/com/moneymong/domain/ledger/api/request/CreateLedgerDocumentRequest.java, src/main/java/com/moneymong/domain/ledger/api/request/SearchLedgerRequest.java, src/main/java/com/moneymong/domain/ledger/api/response/LedgerInfoView.java, src/main/java/com/moneymong/domain/ledger/repository/LedgerDetailRepository.java, src/main/java/com/moneymong/domain/ledger/repository/LedgerDocumentRepository.java, src/main/java/com/moneymong/domain/ledger/repository/LedgerReceiptRepository.java, src/main/java/com/moneymong/domain/ledger/service/manager/LedgerDetailManager.java, src/main/java/com/moneymong/domain/ledger/service/manager/LedgerDocumentManager.java, src/main/java/com/moneymong/domain/ledger/service/manager/LedgerManager.java, src/main/java/com/moneymong/domain/ledger/service/reader/LedgerReader.java, src/main/java/com/moneymong/global/exception/enums/ErrorCode.java
장부 조회(일반적인 조회 API) 기능 구현하였습니다.
=> feat: 장부 조회 - 일반적인 조회  API

.github/workflows/deploy-dev.yml, .gitignore, build.gradle, src/main/java/com/moneymong/domain/user/repository/UserRepository.java, src/main/java/com/moneymong/domain/user/repository/UserRepositoryCustom.java, src/main/java/com/moneymong/domain/user/repository/UserRepositoryImpl.java, src/main/java/com/moneymong/global/config/docs/OpenApiConfig.java, src/main/java/com/moneymong/global/config/jpa/QuerydslConfig.java, src/main/java/com/moneymong/global/config/security/SecurityConfig.java, src/main/resources/application-dev.yml
- QueryDSL 설정을 추가했습니다. QClass 생성 방법은 문서로 남겨놓을게요
- Swagger 테스트 시 JWT를 입력하도록 변경했습니다.
- favicon.ico 등 기타 리소스는 필터 체인을 거치지 않도록 WebSecurityCustomizer를 빈으로 등록했습니다.
=> feat: QueryDSL 설정 및 Swagger Jwt 설정 추가

src/main/java/com/moneymong/domain/invitationcode/entity/InvitationCode.java, src/main/java/com/moneymong/domain/invitationcode/repository/InvitationCodeRepository.java
- 참여코드 엔티티와 Repository를 추가합니다.
=> feat: 참여코드 엔티티와 repository를 생성한다.

src/main/java/com/moneymong/domain/agency/api/AgencyController.java, src/main/java/com/moneymong/domain/agency/api/request/CreateAgencyRequest.java, src/main/java/com/moneymong/domain/agency/api/response/CreateAgencyResponse.java, src/main/java/com/moneymong/domain/agency/entity/Agency.java, src/main/java/com/moneymong/domain/agency/entity/AgencyUser.java, src/main/java/com/moneymong/domain/agency/service/AgencyService.java
소속을 생성하고, 해당 소속에 유저를 추가하는 api입니다.
api 호출 시 
[Agency Table]
[AgencyUser Table]
=> feat: 소속 생성 api를 추가한다.

src/main/java/com/moneymong/domain/agency/entity/Agency.java, src/main/java/com/moneymong/domain/agency/service/AgencyService.java
Agency에 대학 이름 정보를 추가합니다.
교내동아리 / 학생회 소속을 조회할때 이용할 예정입니다.
=> feat: 소속 엔티티에 대학 이름정보를 추가한다.

src/main/java/com/moneymong/domain/university/University.java, src/main/java/com/moneymong/domain/university/api/UniversityController.java, src/main/java/com/moneymong/domain/university/api/response/SearchUniversityResponse.java, src/main/java/com/moneymong/domain/university/api/response/UniversityResponse.java, src/main/java/com/moneymong/domain/university/repository/UniversityRepository.java, src/main/java/com/moneymong/domain/university/repository/UniversityRepositoryCustom.java, src/main/java/com/moneymong/domain/university/repository/UniversityRepositoryImpl.java, src/main/java/com/moneymong/domain/university/service/UniversityService.java
keyword로 대학교를 검색하는 api를 추가합니다.
querydsl contains()를 이용합니다.
=> feat: 대학 검색 api를 구현한다.

src/main/java/com/moneymong/domain/agency/service/AgencyService.java, src/main/java/com/moneymong/domain/ledger/api/LedgerController.java, src/main/java/com/moneymong/domain/ledger/api/LedgerDetailController.java, src/main/java/com/moneymong/domain/ledger/api/LedgerDocumentController.java, src/main/java/com/moneymong/domain/ledger/api/LedgerReceiptController.java, src/main/java/com/moneymong/domain/ledger/api/request/CreateLedgerDocumentRequest.java, src/main/java/com/moneymong/domain/ledger/api/request/CreateLedgerReceiptRequest.java, src/main/java/com/moneymong/domain/ledger/api/request/CreateLedgerRequest.java, src/main/java/com/moneymong/domain/ledger/api/request/SearchLedgerFilterRequest.java, src/main/java/com/moneymong/domain/ledger/api/request/SearchLedgerRequest.java, src/main/java/com/moneymong/domain/ledger/api/request/UpdateLedgerRequest.java, src/main/java/com/moneymong/domain/ledger/entity/enums/FundType.java, src/main/java/com/moneymong/domain/ledger/repository/impl/LedgerDetailCustomImpl.java, src/main/java/com/moneymong/domain/ledger/service/manager/LedgerDetailManager.java, src/main/java/com/moneymong/domain/ledger/service/manager/LedgerDocumentManager.java, src/main/java/com/moneymong/domain/ledger/service/manager/LedgerReceiptManager.java, src/main/java/com/moneymong/domain/ledger/service/reader/LedgerReader.java
- 소속 등록 시 장부 자동 생성 구현
- 권한, 검증 추가
- 그룹에 속한 장부 조회 구현
=> feat: 장부 전반적인 리팩토링

build.gradle, src/main/java/com/moneymong/global/config/p6spy/P6spyConfig.java, src/main/resources/application.yml
p6spy 의존성을 추가합니다(Logging 용도)
개발 서버에만 적용할 예정입니다.
=> feat: P6spy 의존성을 추가한다.

src/main/java/com/moneymong/domain/ledger/api/request/CreateLedgerDocumentRequest.java, src/main/java/com/moneymong/domain/ledger/api/request/CreateLedgerReceiptRequest.java, src/main/java/com/moneymong/domain/ledger/api/request/CreateLedgerRequest.java, src/main/java/com/moneymong/domain/ledger/api/request/SearchLedgerFilterRequest.java, src/main/java/com/moneymong/domain/ledger/api/request/SearchLedgerRequest.java, src/main/java/com/moneymong/domain/ledger/api/request/UpdateLedgerRequest.java, src/main/java/com/moneymong/global/exception/GlobalExceptionHandler.java, src/main/java/com/moneymong/global/exception/dto/ErrorResponses.java
- MethodArgumentNotValidException 발생 시 응답 메시지 커스텀 하였습니다.
=> refactor: MethodArgument 에러 응답 리팩토링

src/main/java/com/moneymong/domain/ledger/api/LedgerController.java, src/main/java/com/moneymong/domain/ledger/repository/LedgerRepository.java, src/main/java/com/moneymong/domain/ledger/service/reader/LedgerReader.java
소속 내에 장부가 존재하는지 조회하는 api를 추가합니다.
[관련 쓰레드](https://moneymong.slack.com/archives/C0665ND7UQY/p1705458465685469)
exists로 해당 소속에 장부가 조회하는지 조회하는 api, 쿼리메소드를 추가합니다.
일단은 boolean을 반환합니다..
장부가 존재하지 않는 소속인 경우
장부가 존재하는 소속인 경우
=> feat: 소속 내에 장부가 존재하는지 조회하는 api를 추가한다.

src/main/java/com/moneymong/domain/user/api/response/UserProfileResponse.java, src/main/java/com/moneymong/domain/user/service/UserService.java
내정보 조회 response에 대학교 이름과 학년 필드를 추가합니다.
=> refactor: 내정보 조회 api의 응답에 대학 정보를 추가한다.

src/main/java/com/moneymong/domain/user/api/UserController.java, src/main/java/com/moneymong/domain/user/service/UserService.java
=> feat: 회원 탈퇴 api를 추가한다.

src/main/java/com/moneymong/domain/ledger/repository/LedgerDetailRepository.java, src/main/java/com/moneymong/domain/ledger/repository/LedgerRepository.java, src/main/java/com/moneymong/domain/ledger/repository/impl/LedgerDetailCustomImpl.java, src/main/java/com/moneymong/domain/ledger/service/reader/LedgerReader.java
소속에 장부가 존재하는지 조회하는 api를 수정합니다.
기존의 Ledger를 조회하던 로직에서 LedgerDetail을 조회하는 로직으로 변경합니다.
=> refactor: 장부 존재 여부를 LedgerDetail 유무로 변경한다.

src/main/java/com/moneymong/domain/invitationcode/entity/InvitationCodeCertification.java, src/main/java/com/moneymong/domain/invitationcode/service/InvitationCodeService.java
초대코드를 인증할때, status의 값을 추가합니다.
status 컬럼을 not null로 추가하고, 코드 수정하는 것을 깜빡했네요,,..
=> fix: 초대코드 인증 정보를 저장할 때 status도 저장한다.

src/main/java/com/moneymong/domain/user/api/UserUniversityController.java, src/main/java/com/moneymong/domain/user/entity/UserUniversity.java, src/main/java/com/moneymong/domain/user/repository/UserUniversityRepository.java, src/main/java/com/moneymong/domain/user/service/UserUniversityService.java
개발 편의를 위해 대학 정보를 삭제하는 api를 추가합니다.
=> feat: 유저의 대학 정보를 삭제하는 api 추가

src/main/java/com/moneymong/domain/agency/entity/Agency.java, src/main/java/com/moneymong/domain/agency/exception/AlreadyAgencyUserExistException.java, src/main/java/com/moneymong/domain/agency/service/AgencyService.java, src/main/java/com/moneymong/domain/agency/service/AgencyUserService.java, src/main/java/com/moneymong/domain/invitationcode/service/InvitationCodeService.java, src/main/java/com/moneymong/global/exception/enums/ErrorCode.java
- 소속 생성 시 초대코드를 같이 생성합니다
- 소속에 가입/강퇴 시 소속의 headCount를 update합니다.
- 초대코드 인증 완료 시, 해당 유저를 소속에 가입시킵니다.
=> refactor: 소속 가입 및 headCount update

.docker/docker-compose.yml, build.gradle, src/main/java/com/moneymong/global/config/redis/RedisConfig.java, src/main/resources/application-dev.yml, src/main/resources/application-local.yml
refreshToken, 초대코드 등을 redis in-memory로 관리할 계획입니다.
- redis config class 추가
- spring-data-redis dependency 추가(lettuce client를 사용합니다.)
=> setting: redis 설정을 추가한다.

src/main/java/com/moneymong/domain/agency/api/AgencyController.java, src/main/java/com/moneymong/domain/agency/repository/AgencyUserRepositoryCustom.java, src/main/java/com/moneymong/domain/agency/repository/AgencyUserRepositoryImpl.java, src/main/java/com/moneymong/domain/agency/service/AgencyService.java
내가 속한 소속의 목록을 조회하는 api를 추가합니다.
=> feat: 내 소속 목록을 조회하는 api를 추가한다.

build.gradle, src/main/java/com/moneymong/global/config/security/SecurityConfig.java, src/main/resources/application.yml
모니터링을 위해 prometheus 설정을 추가합니다.
- micrometer 의존성 추가
- actuator 설정 변경
=> setting: prometheus 설정을 추가한다.

src/main/java/com/moneymong/global/exception/GlobalExceptionHandler.java
exception handler에 warn, error level의 로그를 출력하도록 메소드를 추가합니다.
=> chore: Exception handler에 logging을 추가한다.

src/main/java/com/moneymong/domain/ledger/service/reader/LedgerReader.java
장부를 조회하는 api에서 유저의 권한을 검사합니다.
강퇴된 유저인 경우 예외를 던지도록 합니다.
=> feat: 강퇴된 유저가 장부 조회 시 예외가 발생한다.

src/main/java/com/moneymong/global/exception/enums/ErrorCode.java, src/main/java/com/moneymong/global/security/oauth/handler/KakaoService.java
kakao login 시 토큰값이 유효하지 않은 경우를 처리합니다.
=> feat: kakao 로그인 예외 처리를 세분화한다.

.github/workflows/deploy-dev.yml, src/main/java/com/moneymong/domain/invitationcode/api/InviteCodeController.java, src/main/java/com/moneymong/global/config/docs/OpenApiConfig.java, src/main/java/com/moneymong/global/image/api/ImageController.java, src/main/java/com/moneymong/global/security/token/api/TokenController.java, src/main/resources/application.yml
일부 패키지에 있는 api가 swagger-scan이 안되는 상황
- packages-to-scan 변경
- 누락된 Tag, Operation 추가
=> config: swagger scan 패키지를 수정한다.
